A2_SinhToDau_QuanLyBenhVien/Models/Appointment.cs
using Microsoft.AspNetCore.Components.Routing;
using System.ComponentModel.DataAnnotations;

namespace A2_SinhToDau_QuanLyBenhVien.Models
{
    public class Appointment
    {
        public Guid Id { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public string Time { get; set; }
        [Required]
        public string CustomerName { get; set; }
        [Required]
        public string CustomerEmail { get; set; }
        [Required]
        public string CustomerPhone { get; set; }
        [Required]
        public string CustomerAddress { get; set; }
        [Required]
        public string Reason { get; set; }

        public string Note { get; set; }
        public Guid DoctorsId { get; set; }
        public virtual Doctor? Doctors { get; set; }
    }
}

A2_SinhToDau_QuanLyBenhVien/Models/Degree.cs
using Microsoft.AspNetCore.Components.Routing;
using System.ComponentModel.DataAnnotations;

namespace A2_SinhToDau_QuanLyBenhVien.Models
{
    public class Degree
    {
        public Guid Id { get; set; }
        [Required]
        public string DeContent { get; set; }

        public Guid DoctorsId { get; set; }
        public virtual Doctor? Doctors { get; set; }
    }
}

A2_SinhToDau_QuanLyBenhVien/Areas/Admin/Controllers/ManagerController.cs
using A2_SinhToDau_QuanLyBenhVien.Data;
using A2_SinhToDau_QuanLyBenhVien.Models;
using A2_SinhToDau_QuanLyBenhVien.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Drawing;
using System.Drawing.Imaging;
using System.Numerics;
using A2_SinhToDau_QuanLyBenhVien.Controllers;
namespace A2_SinhToDau_QuanLyBenhVien.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ManagerController : Controller
    {
        private readonly IAppointmentRepository _appointmentRepository;
        private readonly IDoctorRepository _doctorRepository;
        private readonly ISpecialistRepository _specialistRepository;
        private readonly IServiceRepository _serviceRepository;
        private readonly INewsRepository _newsRepository;
        private readonly IDegreeRepository _degreeRepository;
        public ManagerController(ISpecialistRepository specialistRepository, IServiceRepository serviceRepository, INewsRepository newsRepository, IDoctorRepository doctorRepository, IAppointmentRepository appointmentRepository, IDegreeRepository degreeRepository)
        {
            _specialistRepository = specialistRepository;
            _serviceRepository = serviceRepository;
            _newsRepository = newsRepository;
            _appointmentRepository = appointmentRepository;
            _doctorRepository = doctorRepository;
            _degreeRepository = degreeRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Doctor()
        {
            var doctors = await _doctorRepository.GetAllAsync();
            ViewBag.NumberOfDoctors = doctors.Count();
            ViewBag.Spec = GetDoctorsWithSpecialistsAsync();
            return View(doctors);
        }
        public async Task<List<Doctor>> GetDoctorsWithSpecialistsAsync()
        {
            var spec = await _doctorRepository.GetAllDoctorSpecialistAsync();
            return spec;
        }

        public async Task<IActionResult> Service()
        {
            var services = await _serviceRepository.GetAllAsync();
            ViewBag.NumberOfServices = services.Count();
            return View(services);
        }

        public async Task<IActionResult> Specialist()
        {
            var specialists = await _specialistRepository.GetAllAsync();
            ViewBag.NumberOfSpecialists = specialists.Count();
            return View(specialists);
        }
        public async Task<IActionResult> Appointment()
        {
            var appointment = await _appointmentRepository.GetAllAsync();
            ViewBag.NumberOfAppointments = appointment.Count();
            return View(appointment);
        }
        public async Task<IActionResult> Degree()
        {
            var degree = await _degreeRepository.GetAllAsync();
            ViewBag.NumberOfDegrees = degree.Count();
            return View(degree);
        }
        public async Task<IActionResult> New()
        {
            var news = await _newsRepository.GetAllAsync();
            ViewBag.NumberOfNew = news.Count();
            return View(news);
        }
        public async Task<IActionResult> Create()
        {
            var specialists = await _specialistRepository.GetAllAsync();
            ViewBag.Specialists = new SelectList(specialists, "Id", "SpecialistName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Doctor doctor, IFormFile AvtImage)
        {
            ModelState.Remove("AvtImage");
            IsImageValid(AvtImage, "AvtImage");
            if (ModelState.IsValid)
            {
                byte[] arrImage = await ConvertImageToByteArrayAsync(AvtImage);
                doctor.AvtImage = arrImage;
                await _doctorRepository.AddAsync(doctor);
                return RedirectToAction(nameof(Doctor));
            }
            // Nếu ModelState không hợp lệ, hiển thị form với dữ liệu đã nhập
            var specialists = await _specialistRepository.GetAllAsync();
            ViewBag.Specialists = new SelectList(specialists, "Id", "SpecialistName");
            return View(doctor);
        }

        public async Task<IActionResult> CreateNews()
        {
            var specialists = await _specialistRepository.GetAllAsync();
            ViewBag.Specialists = new SelectList(specialists, "Id", "SpecialistName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateNews(New news, IFormFile MainImg)
        {
            ModelState.Remove("MainImg");
            ModelState.Remove("NewsContent");
            IsImageValid(MainImg, "MainImg");
            if (ModelState.IsValid)
            {
                byte[] arrImage = await ConvertImageToByteArrayAsync(MainImg);
                news.MainImg = arrImage;
                await _newsRepository.AddAsync(news);
                return RedirectToAction(nameof(New));
            }
            return View(news);
        }

        public async Task<IActionResult> CreateService()
        {
            var specialists = await _specialistRepository.GetAllAsync();
            ViewBag.Specialists = new SelectList(specialists, "Id", "SpecialistName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateService(Service service, IFormFile MainImg)
        {
            ModelState.Remove("MainImg");
            IsImageValid(MainImg, "MainImg");
            if (ModelState.IsValid)
            {
                byte[] arrImage = await ConvertImageToByteArrayAsync(MainImg);
                service.MainImg = arrImage;
                await _serviceRepository.AddAsync(service);
                return RedirectToAction(nameof(Service));
            }
            return View(service);
        }

        public async Task<IActionResult> CreateSpecialist()
        {
            var specialists = await _specialistRepository.GetAllAsync();
            ViewBag.Specialists = new SelectList(specialists, "Id", "SpecialistName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateSpecialist(Specialist specialist, IFormFile SpecialistImg)
        {
            ModelState.Remove("SpecialistImg");
            IsImageValid(SpecialistImg, "SpecialistImg");
            if (ModelState.IsValid)
            {
                byte[] arrImage = await ConvertImageToByteArrayAsync(SpecialistImg);
                specialist.SpecialistImg = arrImage;
                await _specialistRepository.AddAsync(specialist);
                return RedirectToAction(nameof(Specialist));
            }
            return View(specialist);
        }

        public async Task<IActionResult> CreateAppointment()
        {
            AppointmentController a = new AppointmentController(_specialistRepository, _serviceRepository, _newsRepository, _doctorRepository, _appointmentRepository);
            return await a.MakeAppointment();
            //var specialists = await _specialistRepository.GetAllAsync();
            //ViewBag.Specialists = new SelectList(specialists, "Id", "SpecialistName");
            //return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAppointment(Appointment appointment)
        {
            AppointmentController a = new AppointmentController(_specialistRepository, _serviceRepository, _newsRepository, _doctorRepository, _appointmentRepository);
            return await a.MakeAppointment(appointment);
            //if (ModelState.IsValid)
            //{
            //    await _appointmentRepository.AddAsync(appointment);
            //    return RedirectToAction(nameof(Appointment));
            //}
            //return View(appointment);
        }

        public async Task<IActionResult> CreateDegree()
        {
            var doctor = await _doctorRepository.GetAllAsync();
            ViewBag.Doctors = new SelectList(doctor, "Id", "DrName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateDegree(Degree degree)
        {
            if (ModelState.IsValid)
            {
                await _degreeRepository.AddAsync(degree);
                return RedirectToAction(nameof(Degree));
            }
            var doctor = await _doctorRepository.GetAllAsync();
            ViewBag.Doctors = new SelectList(doctor, "Id", "DrName");
            return View(degree);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteService(Guid id)
        {
            var service = await _serviceRepository.GetByIdAsync(id);
            if (service == null)
            {
                return NotFound();
            }
            await _serviceRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Service));
        }
        public async Task<IActionResult> DeleteNews(Guid id)
        {
            var news = await _newsRepository.GetByIdAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            await _newsRepository.DeleteAsync(id);
            return RedirectToAction(nameof(New));
        }
        [HttpPost]
        public async Task<IActionResult> DeleteSpecialist(Guid id)
        {
            var specialist = await _specialistRepository.GetByIdAsync(id);
            if (specialist == null)
            {
                return NotFound();
            }
            await _specialistRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Specialist));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteDoctor(Guid id)
        {
            var doctor = await _doctorRepository.GetByIdAsync(id);
            if (doctor == null)
            {

A2_SinhToDau_QuanLyBenhVien/Controllers/AppointmentController.cs
using A2_SinhToDau_QuanLyBenhVien.Models;
using A2_SinhToDau_QuanLyBenhVien.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace A2_SinhToDau_QuanLyBenhVien.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly IAppointmentRepository _appointmentRepository;
        private readonly IDoctorRepository _doctorRepository;
        private readonly ISpecialistRepository _specialistRepository;
        private readonly IServiceRepository _serviceRepository;
        private readonly INewsRepository _newsRepository;
        public AppointmentController(ISpecialistRepository specialistRepository, IServiceRepository serviceRepository, INewsRepository newsRepository, IDoctorRepository doctorRepository, IAppointmentRepository appointmentRepository)
        {
            _specialistRepository = specialistRepository;
            _serviceRepository = serviceRepository;
            _newsRepository = newsRepository;
            _appointmentRepository = appointmentRepository;
            _doctorRepository = doctorRepository;
        }
        public async Task<IActionResult> MakeAppointment()
        {
            var specialist = await _specialistRepository.GetAllAsync();
            var service = await _serviceRepository.GetAllAsync();
            var news = await _newsRepository.GetAllAsync();
            var doctors = await _doctorRepository.GetAllAsync();
            ViewBag.service = new SelectList(service, "Id", "SVName");
            ViewBag.specialist = new SelectList(specialist, "Id", "SpecialistName");
            ViewBag.news = new SelectList(news, "Id", "Title");
            ViewBag.doctor = new SelectList(doctors, "Id", "DrName");
            List<string> times = new List<string>();

            for (int hour = 7; hour <= 20; hour++)
            {
                for (int minute = 0; minute < 60; minute += 30)
                {
                    string timeString = $"{hour}h";
                    if (minute != 0)
                    {
                        timeString += $"{minute:D2}";
                    }
                    times.Add(timeString);
                }
            }

            ViewBag.time = new SelectList(times);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> MakeAppointment(Appointment appointment)
        {
            var specialist = await _specialistRepository.GetAllAsync();
            var service = await _serviceRepository.GetAllAsync();
            var news = await _newsRepository.GetAllAsync();
            var doctors = await _doctorRepository.GetAllAsync();
            var appointments = await _appointmentRepository.GetAllAsync();
            List<string> times = new List<string>();
            if (ModelState.IsValid)
            {
                if (appointments.Any(x => x.DoctorsId == appointment.DoctorsId && x.Date == appointment.Date && x.Time == appointment.Time))
                {
                    ModelState.AddModelError(string.Empty, "Thời gian bạn đặt cho bác sĩ " + appointments.FirstOrDefault(x => x.DoctorsId == appointment.DoctorsId).Doctors.DrName + " đã được đặt.");

                    // Hiển thị form với ModelState không hợp lệ
                    ViewBag.service = new SelectList(service, "Id", "SVName");
                    ViewBag.specialist = new SelectList(specialist, "Id", "SpecialistName");
                    ViewBag.news = new SelectList(news, "Id", "Title");
                    ViewBag.doctor = new SelectList(doctors, "Id", "DrName");
                    for (int hour = 7; hour <= 20; hour++)
                    {
                        for (int minute = 0; minute < 60; minute += 30)
                        {
                            string timeString = $"{hour}h";
                            if (minute != 0)
                            {
                                timeString += $"{minute:D2}";
                            }
                            times.Add(timeString);
                        }
                    }

                    ViewBag.time = new SelectList(times);
                    return View(appointment);
                }
                //bool isTimeSlotAvailable = await _appointmentRepository.IsTimeSlotAvailableAsync(appointment.DoctorsId, appointment.Time);
                TempData["SuccessMessage"] = "Đăng ký thành công!";
                await _appointmentRepository.AddAsync(appointment);
                return RedirectToAction("Index", "Home");
            }
            // Nếu ModelState không hợp lệ, hiển thị form với dữ liệu đã nhập
            for (int hour = 7; hour <= 20; hour++)
            {
                for (int minute = 0; minute < 60; minute += 30)
                {
                    string timeString = $"{hour}h";
                    if (minute != 0)
                    {
                        timeString += $"{minute:D2}";
                    }
                    times.Add(timeString);
                }
            }

            ViewBag.time = new SelectList(times);
            ViewBag.service = new SelectList(service, "Id", "SVName");
            ViewBag.specialist = new SelectList(specialist, "Id", "SpecialistName");
            ViewBag.news = new SelectList(news, "Id", "Title");
            ViewBag.doctor = new SelectList(doctors, "Id", "DrName");
            return View(appointment);
        }
        [HttpGet]
        public async Task<IActionResult> GetDoctorsBySpecialist(Guid specialistId)
        {
            try
            {
                // Lấy danh sách các bác sĩ thuộc khoa được chọn từ repository
                var doctors = await _doctorRepository.GetBySpecialistIdAsync(specialistId);

                // Chuyển đổi danh sách này sang một danh sách các đối tượng JSON tương tự như đã làm trong action GetDoctors
                var doctorList = new List<object>();
                foreach (var doctor in doctors)
                {
                    doctorList.Add(new { value = doctor.Id, text = doctor.DrName });
                }

                // Trả về danh sách các bác sĩ dưới dạng JSON
                return Json(doctorList);
            }
            catch (Exception ex)
            {
                // Xử lý ngoại lệ nếu có
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }
    }
}

A2_SinhToDau_QuanLyBenhVien/Areas/Admin/Views/Manager/Appointment.cshtml
@using A2_SinhToDau_QuanLyBenhVien.Areas.Admin.Controllers
@model List<A2_SinhToDau_QuanLyBenhVien.Models.Appointment>
@{
    ViewData["Title"] = "Appointment";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<main>
    <div class="container px-4">
        <h2 class="mt-3 mb-3">Danh sách lịch khám</h2>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Lịch Khám Hiện Có: @ViewBag.NumberOfDoctors
            </div>
            <div class="card-body">
                <table id="datatablesSimple" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Ngày Khám</th>
                            <th>Thời Gian</th>
                            <th>Tên Bệnh Nhân</th>
                            <th>Email</th>
                            <th>Số Điện Thoại</th>
                            <th>Địa Chỉ</th>
                            <th>Lý Do</th>
                            <th>Ghi Chú</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var appointment in Model)
                        {
                            <tr>
                                <td>@appointment.Id</td>
                                <td>@appointment.Date</td>
                                <td>@appointment.Time</td>
                                <td>@appointment.CustomerName</td>                               
                                <td>@appointment.CustomerEmail</td>
                                <td>@appointment.CustomerPhone</td>
                                <td>@appointment.CustomerAddress</td>
                                <td>@appointment.Reason</td>
                                <td>@appointment.Note</td>
                                <td>
                                    <a href="@Url.Action("EditAppointment", "Manager", new { id = appointment.Id })" class="btn btn-primary btn-sm">Edit</a>
                                    <a href="#" class="btn btn-danger btn-sm delete-button" data-id="@appointment.Id">Xóa</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <script src="~/admin/js/datatables-simple-demo.js"></script>
        @section Scripts {
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
            <script>
                $(document).ready(function () {
                    $(document).on('click', '.delete-button', function (e) {
                        e.preventDefault();
                        var Id = $(this).data('id');
                        Swal.fire({
                            title: 'Bạn có chắc chắn muốn xóa?',
                            text: "Bạn sẽ không thể hoàn tác hành động này!",
                            icon: 'warning',
                            showCancelButton: true,
                            confirmButtonColor: '#3085d6',
                            cancelButtonColor: '#d33',
                            confirmButtonText: 'Xóa',
                            cancelButtonText: 'Hủy'
                        }).then((result) => {
                            if (result.isConfirmed) {
                                // Gửi yêu cầu POST để xóa dịch vụ
                                $.ajax({
                                    url: '@Url.Action("DeleteAppointment", "Manager")/' + Id,
                                    type: 'POST',
                                    success: function () {
                                        window.location.reload();
                                    },
                                    error: function () {
                                        Swal.fire({
                                            title: 'Đã xảy ra lỗi!',
                                            text: 'Không thể xóa dịch vụ này.',
                                            icon: 'error',
                                            confirmButtonText: 'OK'
                                        });
                                    }
                                });
                            }
                        });
                    });
                });

            </script>
        }
</main>

A2_SinhToDau_QuanLyBenhVien/Areas/Admin/Views/Manager/EditDegree.cshtml
@model A2_SinhToDau_QuanLyBenhVien.Models.Degree
@{
    ViewData["Title"] = "EditDegree";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="container px-4">
    <h2 class="mt-3 mb-3 ml-3">Sửa Bằng Cấp</h2>
    <hr />
    <div class="row mb-4">
        <div class="col-md-6 offset-md-3">
            <form asp-action="EditDegree" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group mb-2">
                    <label asp-for="Id" class="control-label">ID</label>
                    <input asp-for="Id" class="form-control" />
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
                <div class="form-group mb-2">
                    <label asp-for="DeContent" class="control-label">Bằng Cấp</label>
                    @Html.TextAreaFor(m => m.DeContent, new { @class = "form-control", rows = 3 })
                    <span asp-validation-for="DeContent" class="text-danger"></span>
                </div>
                <div class="form-group mb-2">
                    <label asp-for="DoctorsId" class="control-label">Bác Sĩ</label>
                    <select asp-for="DoctorsId" class="form-control" asp-items="ViewBag.Doctors" class="form-control"></select>
                </div>
                <br />
                <button type="submit" class="btn btn-primary">Cập Nhật</button>
            </form>
        </div>
    </div>
</div>

A2_SinhToDau_QuanLyBenhVien/Areas/Admin/Views/Manager/New.cshtml
@model List<A2_SinhToDau_QuanLyBenhVien.Models.New>
@{
    ViewData["Title"] = "New";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="container px-4">
    <h2 class="mt-3 mb-3">Danh Sách Bác Sĩ</h2>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Bác Sĩ Hiện Có: @ViewBag.NumberOfDoctors
        </div>
        <div class="card-body">
            <table id="datatablesSimple" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tiêu Đề</th>
                        <th>Giới Thiệu</th>
                        <th>Ảnh Nền</th>
                        <th>Nội Dung</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var news in Model)
                    {
                        <tr>
                            <td>@news.Id</td>
                            <td>@news.Title</td>
                            <td>@news.NewsTeaser</td>
                            <td><img src="data:image/jpeg;base64,@(Convert.ToBase64String(news.MainImg))" width="100" height="100" /> </td>
                            <td>@news.NewsContent</td>
                            <td>
                                <a href="@Url.Action("EditNews", "Manager", new { id = news.Id })" class="btn btn-primary btn-sm">Sửa</a>
                                <a href="#" class="btn btn-danger btn-sm delete-button" data-id="@news.Id">Xóa</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <script src="~/admin/js/datatables-simple-demo.js"></script>
    @section Scripts {
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script>
            $(document).ready(function () {
                $(document).on('click', '.delete-button', function (e) {
                    e.preventDefault();
                    var Id = $(this).data('id');
                    Swal.fire({
                        title: 'Bạn có chắc chắn muốn xóa?',
                        text: "Bạn sẽ không thể hoàn tác hành động này!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Xóa',
                        cancelButtonText: 'Hủy'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            $.ajax({
                                url: '@Url.Action("DeleteNews", "Manager")/' + Id,
                                type: 'POST',
                                success: function () {
                                    window.location.reload();
                                },
                                error: function () {
                                    Swal.fire({
                                        title: 'Đã xảy ra lỗi!',
                                        text: 'Không thể xóa dịch vụ này.',
                                        icon: 'error',
                                        confirmButtonText: 'OK'
                                    });
                                }
                            });
                        }
                    });
                });
            });
        </script>
    }

A2_SinhToDau_QuanLyBenhVien/Areas/Admin/Views/Manager/Specialist.cshtml
@using A2_SinhToDau_QuanLyBenhVien.Areas.Admin.Controllers
@model List<A2_SinhToDau_QuanLyBenhVien.Models.Specialist>
@{
    ViewData["Title"] = "Specialist";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="container px-4">
    <h2 class="mt-3 mb-3">Danh Sách Chuyên Ngành</h2>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Chuyên Ngành Hiện Có: @ViewBag.NumberOfSpecialists
        </div>
        <div class="card-body">
            <table id="datatablesSimple" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên Chuyên Ngành</th>
                        <th>Ảnh Nền</th>
                        <th>Mô Tả</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var specialist in Model)
                    {
                        <tr>
                            <td>@specialist.Id</td>
                            <td>@specialist.SpecialistName</td>
                            <td><img src="data:image/jpeg;base64,@(Convert.ToBase64String(specialist.SpecialistImg))" width="100" height="100" /> </td>
                            <td>@specialist.SpecialistDescription</td>
                            <td>
                                <a href="@Url.Action("EditSpecialist", "Manager", new { id = specialist.Id })" class="btn btn-primary btn-sm">Edit</a>
                                <a href="#" class="btn btn-danger btn-sm delete-button" data-id="@specialist.Id">Xóa</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $(document).ready(function () {
            $(document).on('click', '.delete-button', function (e) {
                e.preventDefault();
                var Id = $(this).data('id');
                Swal.fire({
                    title: 'Bạn có chắc chắn muốn xóa?',
                    text: "Bạn sẽ không thể hoàn tác hành động này!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Xóa',
                    cancelButtonText: 'Hủy'
                }).then((result) => {
                    if (result.isConfirmed) {
                        // Gửi yêu cầu POST để xóa dịch vụ
                        $.ajax({
                            url: '@Url.Action("DeleteSpecialist", "Manager")/' + Id,
                            type: 'POST',
                            success: function () {
                                window.location.reload();
                            },
                            error: function () {
                                Swal.fire({
                                    title: 'Đã xảy ra lỗi!',
                                    text: 'Không thể xóa dịch vụ này.',
                                    icon: 'error',
                                    confirmButtonText: 'OK'
                                });
                            }
                        });
                    }
                });
            });
        });

    </script>
}