A2_SinhToDau_QuanLyBenhVien/Models/Specialist.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace A2_SinhToDau_QuanLyBenhVien.Models
{
    public class Specialist
    {
        public Guid Id { get; set; }
        [Required]
        public string SpecialistName { get; set; }
        [Required]
        public string SpecialistDescription { get; set; }
        [Required]
        public byte[] SpecialistImg {  get; set; }
        [ForeignKey("EmployeeId")]
        public virtual ApplicationUser? ApplicationUser { get; set; }
        public virtual List<Doctor>? Doctors { get; set; }
    }
}

A2_SinhToDau_QuanLyBenhVien/Controllers/SpecialistController.cs
using A2_SinhToDau_QuanLyBenhVien.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace A2_SinhToDau_QuanLyBenhVien.Controllers
{
    public class SpecialistController : Controller
    {
        private readonly ISpecialistRepository _specialistRepository;
        private readonly IServiceRepository _serviceRepository;
        private readonly INewsRepository _newsRepository;
        public SpecialistController(ISpecialistRepository specialistRepository, IServiceRepository serviceRepository, INewsRepository newsRepository)
        {
            _specialistRepository = specialistRepository;
            _serviceRepository = serviceRepository;
            _newsRepository = newsRepository;
        }
        public async Task<IActionResult> Index()
        {
            var specialist = await _specialistRepository.GetAllAsync();
            var service = await _serviceRepository.GetAllAsync();
            var news = await _newsRepository.GetAllAsync();
            ViewBag.service = new SelectList(service, "Id", "SVName");
            ViewBag.specialist = new SelectList(specialist, "Id", "SpecialistName");
            ViewBag.news = new SelectList(news, "Id", "Title");
            return View(specialist);
        }
        public async Task<IActionResult> Detail(Guid id)
        {
            var specialist = await _specialistRepository.GetByIdAsync(id);
            if (specialist == null)
            {
                return NotFound();
            }
            var specialists = await _specialistRepository.GetAllAsync();
            var service = await _serviceRepository.GetAllAsync();
            var news = await _newsRepository.GetAllAsync();
            ViewBag.service = new SelectList(service, "Id", "SVName");
            ViewBag.specialist = new SelectList(specialists, "Id", "SpecialistName");
            ViewBag.news = new SelectList(news, "Id", "Title");
            return View(specialist);
        }
    }
}

A2_SinhToDau_QuanLyBenhVien/Views/Specialist/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model A2_SinhToDau_QuanLyBenhVien.Models.Specialist
<div class="container">
    <div class="section-title mb-3 justify-content-center">
        <p class="d-flex justify-content-center m-0">@Model.SpecialistName</p>
        <p class="d-flex justify-content-center m-0">🍀</p>
    </div>
    <section>
        @Html.Raw(Model.SpecialistDescription)
    </section>
</div>

A2_SinhToDau_QuanLyBenhVien/Views/Specialist/Index.cshtml
@model IEnumerable<A2_SinhToDau_QuanLyBenhVien.Models.Specialist>
<div class="container">
    <div class="section-title mb-5">
        <p class="d-flex justify-content-center">DANH SÁCH CHUYÊN KHOA</p>
    </div>

    <div class="row row-cols-1 row-cols-md-2 g-4">
        @* ====================================COL============================= *@
        @{
            foreach(var specialist in Model)
            {
                <div class="col mt-0 mb-4" id="col">
                    <div class="special-item d-flex flex-nowrap">
                        <div class="images-wrap">
                            <img src="data:image/jpeg;base64,@(Convert.ToBase64String(specialist.SpecialistImg))" alt="@specialist.SpecialistName"/>
                        </div>
                        <div class="content">
                            <div class="sub-title">
                                <a class="btn" asp-area="" asp-controller="Specialist" asp-action="Detail" asp-route-id="@specialist.Id" style="color: #9d4edd; font-size:16px;font-weight:bolder;">@specialist.SpecialistName</a>
                            </div>
                            <div class="btn-left">
                                <a class="btn" asp-area="" asp-controller="Specialist" asp-action="Detail" asp-route-id="@specialist.Id">Xem chi tiết</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>